{% set name = "ciriquant" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CIRIquant-{{ version }}.tar.gz
  sha256: b3e023b9cce103419867751799d9672b7eb1e0fb945ca8d57d3f8369e3914120

build:
  noarch: python
  number: 0
  script:  python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python ==2.7.15
    - pip ==19.3.1
  run:
    - python ==2.7.15
    - pip ==19.3.1

test:
  commands:
    - CIRIquant --help

about:
  home: https://github.com/bioinfo-biols/CIRIquant
  license: MIT
  license_file: LICENSE
  summary: CIRIquant is a comprehensive analysis pipeline for circRNA detection and quantification in RNA-Seq data
