{% set version = "1.1.2" %}
{% set sha256 = "aad16e65a75fb67b07641acfe31555af972b7457365a4f5d0b234aa10cae7dba" %}

package:
  name: ciriquant
  version: {{ version }}

source:
  url: https://github.com/bioinfo-biols/CIRIquant/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: ciriquant.patch

build:
  noarch: generic
  number: 0
  script: python setup.py install

requirements:
  run:
    - python
    - numexpr==2.6.9
    - numpy==1.22.0
    - pysam==0.15.2
    - PyYAML==5.4.1
    - scikit-learn==0.20.3
    - scipy>=1.2.2
    - argparse>=1.2.1

test:
  commands:
    - CIRIquant --help

about:
  home: https://github.com/bioinfo-biols/CIRIquant
  license: MIT
  license_file: LICENSE
  summary: CIRIquant is a comprehensive analysis pipeline for circRNA detection and quantification in RNA-Seq data
