{% set name = "find_circ" %}
{% set version = "1.2" %}
{% set sha256 = "f88bf9b5d0cc818313074982d4460c96706f555d924e2821832c3d03bf67743e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/marvin-jens/find_circ/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - python ==2.7.15
    - pip
  run:
    - python ==2.7.15
    - numpy ==1.16.4
    - pysam ==0.15.2

test:
  imports:
    - numpy
    - pysam
  commands:
    - python --version
    - which find_circ.py

about:
  home: https://github.com/marvin-jens/find_circ
  license: GPL-3
  license_file: LICENSE
  summary: Detect head-to-tail spliced (back-spliced) sequencing reads, indicative of circular RNA (circRNA) in RNA-seq data.

extra:
  skip-lints:
    - uses_vcs_url
    - missing_hash
