{% set name = "find_circ" %}
{% set version = "1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/marvin-jens/find_circ.git
  git_rev: 8655dca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python ==2.7.15
    - pip
  run:
    - python ==2.7.15
    - numpy ==1.16.4
    - pysam ==0.15.2

test:
  commands:
    - python --version
    - test -f find_circ.py && echo "found"

about:
  home: https://github.com/marvin-jens/find_circ
  license: GPL-3
  license_file: LICENSE.txt
  summary: detect head-to-tail spliced (back-spliced) sequencing reads, indicative of circular RNA (circRNA) in RNA-seq data.

extra:
  skip-lints:
    - uses_vcs_url
    - missing_hash
